---
controller_execution_environments:
  - name: "demo_ee"
    description: ""
    image: "rhel8.hyperv.corvus.local/workshop_ee:latest"
    pull: "missing"
    credential: "Automation Hub Container Registry"
  - name: "Quay Workshop EE"
    description: ""
    image: "quay.io/acme_corp/workshop_ee:latest"
    pull: "missing"
  - name: "workshop_ee_pv"
    description: ""
    image: "rhel8.hyperv.corvus.local/workshop_ee_pv:latest"
    pull: "missing"
    credential: "Automation Hub Container Registry"
  - name: "workshop_ee"
    description: ""
    image: "rhel8.hyperv.corvus.local/workshop_ee:latest"
    pull: "missing"
    credential: "Automation Hub Container Registry"
  - name: "Control Plane Execution Environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:latest"
    pull: ""
  - name: "Default execution environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:latest"
    pull: "missing"
  - name: "Ansible Engine 2.9 execution environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-23/ee-29-rhel8:latest"
    pull: ""
  - name: "Minimal execution environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest"
    pull: ""
...
