---
controller_settings:
  - settings:
      ACTIVITY_STREAM_ENABLED: true
      ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC: true
      ORG_ADMINS_CAN_SEE_ALL_USERS: true
      MANAGE_ORGANIZATION_AUTH: true
      TOWER_URL_BASE: https://127.0.0.1
      REMOTE_HOST_HEADERS: ['REMOTE_ADDR', 'REMOTE_HOST']
      PROXY_IP_ALLOWED_LIST: []
      LICENSE: {'subscription_name': 'Employee SKU', 'sku': 'ES0113909', 'support_level': 'Self-Support', 'instance_count': 9999999, 'license_date': 1692071999, 'license_type': 'enterprise', 'product_name': 'Red Hat Ansible Automation Platform', 'valid_key': true, 'satellite': null, 'pool_id': '2c94b92882fed28e0183315553db4241'}
      REDHAT_USERNAME: cmcaskill
      REDHAT_PASSWORD: $encrypted$
      SUBSCRIPTIONS_USERNAME: cmcaskill
      SUBSCRIPTIONS_PASSWORD: $encrypted$
      INSTALL_UUID: 7ca6ea6f-55ca-406e-b1c6-15a1e2c169c0
      DEFAULT_EXECUTION_ENVIRONMENT: 3
      AD_HOC_COMMANDS: ['command', 'shell', 'yum', 'apt', 'apt_key', 'apt_repository', 'apt_rpm', 'service', 'group', 'user', 'mount', 'ping', 'selinux', 'setup', 'win_ping', 'win_service', 'win_updates', 'win_group', 'win_user']
      ALLOW_JINJA_IN_EXTRA_VARS: always
      AWX_ISOLATION_BASE_PATH: /tmp
      AWX_ISOLATION_SHOW_PATHS: ['/etc/pki/ca-trust:/etc/pki/ca-trust:O', '/usr/share/pki:/usr/share/pki:O']
      AWX_TASK_ENV: {}
      GALAXY_TASK_ENV: {'ANSIBLE_FORCE_COLOR': 'true', 'GIT_SSH_COMMAND': 'ssh -o StrictHostKeyChecking=no', 'GALAXY_DISABLE_GPG_VERIFY': 'true'}
      INSIGHTS_TRACKING_STATE: true
      PROJECT_UPDATE_VVV: true
      AWX_ROLES_ENABLED: true
      AWX_COLLECTIONS_ENABLED: true
      AWX_SHOW_PLAYBOOK_LINKS: false
      AWX_MOUNT_ISOLATED_PATHS_ON_K8S: false
      GALAXY_IGNORE_CERTS: true
      MAX_WEBSOCKET_EVENT_RATE: 30
      SCHEDULE_MAX_JOBS: 10
      AWX_ANSIBLE_CALLBACK_PLUGINS: []
      DEFAULT_JOB_TIMEOUT: 0
      DEFAULT_JOB_IDLE_TIMEOUT: 0
      DEFAULT_INVENTORY_UPDATE_TIMEOUT: 0
      DEFAULT_PROJECT_UPDATE_TIMEOUT: 0
      ANSIBLE_FACT_CACHE_TIMEOUT: 0
      MAX_FORKS: 200
      # AUTOMATION_ANALYTICS_LAST_GATHER: 2023-04-19T18:27:10.456678Z
      # AUTOMATION_ANALYTICS_LAST_ENTRIES: "{\"config\": \"2023-04-19T18:27:10.456Z\", \"counts\": \"2023-04-19T18:27:10.456Z\", \"cred_type_counts\": \"2023-04-19T18:27:10.456Z\", \"instance_info\": \"2023-04-19T18:27:10.456Z\", \"inventory_counts\": \"2023-04-19T18:27:10.456Z\", \"org_counts\": \"2023-04-19T18:27:10.456Z\", \"projects_by_scm_type\": \"2023-04-19T18:27:10.456Z\", \"query_info\": \"2023-04-19T18:27:10.456Z\", \"events_table\": \"2023-04-19T18:27:10.456Z\", \"unified_job_template_table\": \"2023-04-19T18:27:10.456Z\", \"unified_jobs_table\": \"2023-04-19T18:27:10.456Z\", \"workflow_job_node_table\": \"2023-04-19T18:27:10.456Z\", \"workflow_job_template_node_table\": \"2023-04-19T18:27:10.456Z\"}"
      AUTOMATION_ANALYTICS_GATHER_INTERVAL: 7200
      SESSION_COOKIE_AGE: 18000
      SESSIONS_PER_USER: -1
      DISABLE_LOCAL_AUTH: false
      AUTH_BASIC_ENABLED: true
      OAUTH2_PROVIDER: {'ACCESS_TOKEN_EXPIRE_SECONDS': 31536000000, 'REFRESH_TOKEN_EXPIRE_SECONDS': 2628000, 'AUTHORIZATION_CODE_EXPIRE_SECONDS': 600}
      ALLOW_OAUTH2_FOR_EXTERNAL_USERS: false
      LOGIN_REDIRECT_OVERRIDE: 
      PENDO_TRACKING_STATE: detailed
      CUSTOM_LOGIN_INFO: ""
      CUSTOM_LOGO: ""
      SOCIAL_AUTH_ORGANIZATION_MAP: null
      SOCIAL_AUTH_TEAM_MAP: null
      SOCIAL_AUTH_USER_FIELDS: null
      AUTH_LDAP_GROUP_TYPE_PARAMS: {'name_attr': 'cn', 'member_attr': 'member'}
...
