---
controller_credentials:
  - name: "Configuration as Code Credential"
    description: ""
    credential_type: "Configuration as Code"
    organization: "Default"
    inputs:
      controller_password: ''
      controller_username: admin

...
