---
- name: Export all assets
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  - "../group_vars/vaults/vault"
  collections:
    - awx.awx
  environment:
    CONTROLLER_HOST: "{{ vault_controller_hostname }}"
    CONTROLLER_USERNAME: "{{ vault_controller_username }}"
    CONTROLLER_PASSWORD: "{{ vault_controller_password }}"
    CONTROLLER_VERIFY_SSL: false

  tasks:
    - name: Export everything using awx.awx.export
      awx.awx.export:
        all: true
      register: export_results

    - name: Registering export results
      ansible.builtin.debug:
        var: export_results

    - name: Export everything to file
      ansible.builtin.copy:
        content: "{{ export_results | to_nice_yaml }}"
        dest: "../group_vars/allassets"
