---
- name: Import all assets
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  - "../group_vars/vaults/vault"
  # - "../allassets"
  collections:
    - awx.awx
  environment:
    CONTROLLER_HOST: "{{ vault_controller_hostname }}"
    CONTROLLER_USERNAME: "{{ vault_controller_username }}"
    CONTROLLER_PASSWORD: "{{ vault_controller_password }}"
    CONTROLLER_VERIFY_SSL: false

  tasks:
    - name: Import everything using awx.awx.import
      awx.awx.import:
        assets: "{{ lookup('file', '../allassets_nice.yml') | from_yaml() }}"
      register: import_results

    - name: Registering import results
      ansible.builtin.debug:
        var: import_results
...

