---
controller_credentials:
  - name: "AWS Open Environment"
    description: ""
    credential_type: "Amazon Web Services"
    organization: "Default"
    inputs:
      password: ''
      username: AKIA2Y23TWOB3SUJLOXG

...
