---
controller_credentials:
  - name: "Default Execution Environment Registry Credential"
    description: ""
    credential_type: "Container Registry"
    inputs:
      host: quay.io
      password: ''
      username: cmcaskil@redhat.com
      verify_ssl: true

...
