---
# Personal console.redhat.com automation hub token 04/27/2023
consolepriv_token: "{{vault_consolepriv_token}}"

# Personal Red Hat offline token 04/27/2023
offlinepriv_token: "{{vault_offlinepriv_token}}"                                                                                                                              

# Employee console.redhat.com token 04/27/2023
consoleemp_token: "{{vault_consoleemp_token}}"

# Employee Red Hat offline token 04/27/2023
offlineemp_token: "{{vault_offlineemp_token}}"

# Personal Red Hat and container registry credentials
rhpriv_username: "{{vault_rhpriv_username}}"
rhpriv_password: "{{vault_rhpriv_password}}"

# Employee Red Hat and container registry credentials
rhemp_username: "{{vault_rhemp_username}}"
rhemp_password: "{{vault_rhemp_password}}"

# Root password
root_machine_pass: "{{vault_root_machine_pass}}"

# Automation hub credentials
ah_pass: "{{vault_ah_pass}}"
ah_host: "{{vault_ah_host}}"
ah_token: "{{vault_ah_token}}"
ah_token_password: "{{vault_ah_token_password}}"
ah_username: "{{vault_ah_username}}"
ah_path_prefix: 'galaxy' # this is for private automation hub
ah_validate_certs: "false"

# Vault password
vault_pass: "{{vault_vault_pass}}"

# Automation Controller credentials
controller_hostname: "{{vault_controller_hostname}}"
controller_username: "{{vault_controller_username}}"
controller_password: "{{vault_controller_password}}"
controller_api_user_pass: "{{vault_controller_api_user_pass}}"
controller_pass: "{{vault_controller_pass}}"
controller_validate_certs: "false"

pi_password: "{{vault_pi_password}}"




github_token: "{{vault_github_token}}"

# controller.hyperv.corvus.local private key
github_key: "{{vault_github_key}}"

# Personal AWS credentials
aws_personal_access_key: "{{vault_aws_personal_access_key}}"
aws_personal_secret: "{{vault_aws_personal_secret}}"

# AWS open environment credentials
aws_open_access_key: "{{vault_aws_open_access_key}}"
aws_open_secret: "{{vault_aws_open_secret}}"
...